(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(*10x times faster than Export*)
ClearAll[writeYourTSV];
writeYourTSV[file_String,list_List?MatrixQ]:=With[{str=OpenWrite[file,PageWidth->Infinity],len=Length[list[[1]]]},Scan[Write[str,Sequence@@(Flatten[Table[{(*FortranForm[*)#[[i]](*]*),OutputForm["\t"]},{i,len-1}]])~Join~{(*FortranForm[*)#[[len]](*]*)}]&,list];Close[str];](*150211 removed FortranForm because it induced e's*)(*150219 re enabled the fortran form -- Importing seems to work just fine*)
(*150211 removed FortranForm because it induced e's  -- appeared on the remove project*)



